const RENTAL_CATEGORIES = [
  {
    name: "Event & Party Supplies",
    shortName: "Event & Party",
    slug: "event-party",
    icon: "🎉",
    type: "category",
    parentCategory: null,
    subCategories: [
      {
        name: "Chairs & tables (folding, banquet, cocktail)",
        slug: "chairs-tables",
        icon: "🪑",
        type: "category",
        parentCategory: "event-party",
      },
      {
        name: "Tents & canopies",
        slug: "tents-canopies",
        icon: "⛺",
        type: "category",
        parentCategory: "event-party",
      },
      {
        name: "Sound systems & speakers",
        slug: "sound-systems",
        icon: "🔊",
        type: "category",
        parentCategory: "event-party",
      },
      {
        name: "Projectors & screens",
        slug: "projectors-screens",
        icon: "📽️",
        type: "category",
        parentCategory: "event-party",
      },
      {
        name: "Party decorations (backdrops, banners, balloons)",
        slug: "party-decorations",
        icon: "🎈",
        type: "category",
        parentCategory: "event-party",
      },
      {
        name: "Lighting equipment (LEDs, fairy lights, stage lighting)",
        slug: "lighting-equipment",
        icon: "💡",
        type: "category",
        parentCategory: "event-party",
      },
      {
        name: "Dance floors & stages",
        slug: "dance-floors",
        icon: "💃",
        type: "category",
        parentCategory: "event-party",
      },
      {
        name: "Fog machines & bubble machines",
        slug: "fog-bubble-machines",
        icon: "🌫️",
        type: "category",
        parentCategory: "event-party",
      },
      {
        name: "Photo booths & props",
        slug: "photo-booths",
        icon: "📸",
        type: "category",
        parentCategory: "event-party",
      },
      {
        name: "Catering equipment (chafing dishes, coolers, beverage dispensers)",
        slug: "catering-equipment",
        icon: "🥘",
        type: "category",
        parentCategory: "event-party",
      },
    ],
  },
  {
    name: "Photography & Video Equipment",
    shortName: "Cameras",
    slug: "photography-video",
    icon: "📷",
    type: "category",
    parentCategory: null,
    subCategories: [
      {
        name: "DSLR & mirrorless cameras",
        slug: "cameras",
        icon: "📸",
        type: "category",
        parentCategory: "photography-video",
      },
      {
        name: "Camera lenses",
        slug: "camera-lenses",
        icon: "🔭",
        type: "category",
        parentCategory: "photography-video",
      },
      {
        name: "Tripods & stabilizers (gimbals)",
        slug: "tripods-stabilizers",
        icon: "🛠️",
        type: "category",
        parentCategory: "photography-video",
      },
      {
        name: "Drones (DJI, GoPro)",
        slug: "drones",
        icon: "🚁",
        type: "category",
        parentCategory: "photography-video",
      },
      {
        name: "Action cameras (GoPro, Insta360)",
        slug: "action-cameras",
        icon: "📹",
        type: "category",
        parentCategory: "photography-video",
      },
      {
        name: "Lighting kits (softboxes, ring lights, LED panels)",
        slug: "lighting-kits",
        icon: "💡",
        type: "category",
        parentCategory: "photography-video",
      },
      {
        name: "Green screens",
        slug: "green-screens",
        icon: "🟢",
        type: "category",
        parentCategory: "photography-video",
      },
      {
        name: "Microphones & audio recorders",
        slug: "microphones",
        icon: "🎤",
        type: "category",
        parentCategory: "photography-video",
      },
    ],
  },
  {
    name: "Outdoor & Adventure Gear",
    shortName: "Recretional Gear",
    slug: "outdoor-adventure",
    icon: "⛺",
    type: "category",
    parentCategory: null,
    subCategories: [
      {
        name: "Camping tents & sleeping bags",
        slug: "camping-tents",
        icon: "🏕️",
        type: "category",
        parentCategory: "outdoor-adventure",
      },
      {
        name: "Hammocks & air mattresses",
        slug: "hammocks",
        icon: "🌴",
        type: "category",
        parentCategory: "outdoor-adventure",
      },
      {
        name: "Camping stoves & cookware",
        slug: "camping-stoves",
        icon: "🔥",
        type: "category",
        parentCategory: "outdoor-adventure",
      },
      {
        name: "Fishing rods & tackle",
        slug: "fishing-gear",
        icon: "🎣",
        type: "category",
        parentCategory: "outdoor-adventure",
      },
      {
        name: "Kayaks, canoes & paddleboards",
        slug: "water-vessels",
        icon: "🛶",
        type: "category",
        parentCategory: "outdoor-adventure",
      },
      {
        name: "Surfboards & bodyboards",
        slug: "surfboards",
        icon: "🏄",
        type: "category",
        parentCategory: "outdoor-adventure",
      },
      {
        name: "Bicycles & mountain bikes",
        slug: "bicycles",
        icon: "🚲",
        type: "category",
        parentCategory: "outdoor-adventure",
      },
      {
        name: "Hiking gear (backpacks, trekking poles)",
        slug: "hiking-gear",
        icon: "🥾",
        type: "category",
        parentCategory: "outdoor-adventure",
      },
      {
        name: "Snowboarding & skiing equipment",
        slug: "snow-sports",
        icon: "🏂",
        type: "category",
        parentCategory: "outdoor-adventure",
      },
      {
        name: "Binoculars & GPS devices",
        slug: "navigation-gear",
        icon: "🧭",
        type: "category",
        parentCategory: "outdoor-adventure",
      },
    ],
  },
  {
    name: "Tools & Home Improvement",
    shortName: "Home Tools",
    slug: "tools-home",
    icon: "🔨",
    type: "category",
    parentCategory: null,
    subCategories: [
      {
        name: "Power tools (drills, saws, sanders)",
        slug: "power-tools",
        icon: "🛠️",
        type: "category",
        parentCategory: "tools-home",
      },
      {
        name: "Ladders & scaffolding",
        slug: "ladders",
        icon: "🪜",
        type: "category",
        parentCategory: "tools-home",
      },
      {
        name: "Pressure washers",
        slug: "pressure-washers",
        icon: "💦",
        type: "category",
        parentCategory: "tools-home",
      },
      {
        name: "Carpet cleaners & steam cleaners",
        slug: "carpet-cleaners",
        icon: "🧼",
        type: "category",
        parentCategory: "tools-home",
      },
      {
        name: "Generators & inverters",
        slug: "generators",
        icon: "⚡",
        type: "category",
        parentCategory: "tools-home",
      },
      {
        name: "Tile cutters & flooring tools",
        slug: "flooring-tools",
        icon: "🧱",
        type: "category",
        parentCategory: "tools-home",
      },
      {
        name: "Paint sprayers & wallpaper removers",
        slug: "painting-tools",
        icon: "🎨",
        type: "category",
        parentCategory: "tools-home",
      },
      {
        name: "Demolition hammers",
        slug: "demolition-hammers",
        icon: "🔨",
        type: "category",
        parentCategory: "tools-home",
      },
    ],
  },
  {
    name: "Luxury & Specialty Items",
    shortName: "Luxuries",
    slug: "luxury-specialty",
    icon: "💎",
    type: "category",
    parentCategory: null,
    subCategories: [
      {
        name: "Luxury cars (sports cars, convertibles, limos)",
        slug: "luxury-cars",
        icon: "🚗",
        type: "category",
        parentCategory: "luxury-specialty",
      },
      {
        name: "Designer handbags & watches",
        slug: "designer-accessories",
        icon: "👜",
        type: "category",
        parentCategory: "luxury-specialty",
      },
      {
        name: "High-end jewelry & accessories",
        slug: "jewelry",
        icon: "💍",
        type: "category",
        parentCategory: "luxury-specialty",
      },
      {
        name: "Vintage & classic cars",
        slug: "vintage-cars",
        icon: "🚓",
        type: "category",
        parentCategory: "luxury-specialty",
      },
      {
        name: "Private yachts & boats",
        slug: "yachts",
        icon: "🛥️",
        type: "category",
        parentCategory: "luxury-specialty",
      },
    ],
  },
  {
    name: "Electronics & Tech Gadgets",
    shortName: "Electronics & Console",
    slug: "electronics-tech",
    icon: "💻",
    type: "category",
    parentCategory: null,
    subCategories: [
      {
        name: "Laptops & tablets",
        slug: "computers",
        icon: "💻",
        type: "category",
        parentCategory: "electronics-tech",
      },
      {
        name: "Gaming consoles (PS5, Xbox, Nintendo Switch)",
        slug: "gaming-consoles",
        icon: "🎮",
        type: "category",
        parentCategory: "electronics-tech",
      },
      {
        name: "VR headsets (Oculus, HTC Vive)",
        slug: "vr-headsets",
        icon: "🥽",
        type: "category",
        parentCategory: "electronics-tech",
      },
      {
        name: "Smart projectors & screens",
        slug: "projectors",
        icon: "📽️",
        type: "category",
        parentCategory: "electronics-tech",
      },
      {
        name: "Printers & scanners",
        slug: "printers",
        icon: "🖨️",
        type: "category",
        parentCategory: "electronics-tech",
      },
      {
        name: "Walkie-talkies & communication devices",
        slug: "communication-devices",
        icon: "📡",
        type: "category",
        parentCategory: "electronics-tech",
      },
    ],
  },
  {
    name: "Wedding & Formal Wear",
    shortName: "Wedding Formal",
    slug: "wedding-formal",
    icon: "👗",
    type: "category",
    parentCategory: null,
    subCategories: [
      {
        name: "Wedding dresses & tuxedos",
        slug: "wedding-attire",
        icon: "👰",
        type: "category",
        parentCategory: "wedding-formal",
      },
      {
        name: "Evening gowns & suits",
        slug: "evening-wear",
        icon: "🕴️",
        type: "category",
        parentCategory: "wedding-formal",
      },
      {
        name: "Accessories (clutches, veils, gloves)",
        slug: "wedding-accessories",
        icon: "👒",
        type: "category",
        parentCategory: "wedding-formal",
      },
      {
        name: "Traditional outfits (kimono, saree, qipao)",
        slug: "traditional-wear",
        icon: "🥻",
        type: "category",
        parentCategory: "wedding-formal",
      },
    ],
  },
  {
    name: "Sports & Fitness Equipment",
    shortName: "Sports Equipment",
    slug: "sports-fitness",
    icon: "🏋️‍♂️",
    type: "category",
    parentCategory: null,
    subCategories: [
      {
        name: "Treadmills & stationary bikes",
        slug: "cardio-machines",
        icon: "🚴",
        type: "category",
        parentCategory: "sports-fitness",
      },
      {
        name: "Dumbbells & barbells",
        slug: "weights",
        icon: "🏋️",
        type: "category",
        parentCategory: "sports-fitness",
      },
      {
        name: "Yoga mats & resistance bands",
        slug: "yoga-equipment",
        icon: "🧘",
        type: "category",
        parentCategory: "sports-fitness",
      },
      {
        name: "Basketballs, soccer balls, volleyball nets",
        slug: "sports-balls",
        icon: "⚽",
        type: "category",
        parentCategory: "sports-fitness",
      },
      {
        name: "Tennis rackets & golf clubs",
        slug: "racket-sports",
        icon: "🎾",
        type: "category",
        parentCategory: "sports-fitness",
      },
      {
        name: "Boxing gloves & punching bags",
        slug: "boxing-equipment",
        icon: "🥊",
        type: "category",
        parentCategory: "sports-fitness",
      },
    ],
  },
  {
    name: "Medical & Healthcare Equipment",
    shortName: "Healthcare Equipment",
    slug: "medical-healthcare",
    icon: "🏥",
    type: "category",
    parentCategory: null,
    subCategories: [
      {
        name: "Wheelchairs & mobility scooters",
        slug: "mobility-aids",
        icon: "🦽",
        type: "category",
        parentCategory: "medical-healthcare",
      },
      {
        name: "Crutches & walkers",
        slug: "walking-aids",
        icon: "🦯",
        type: "category",
        parentCategory: "medical-healthcare",
      },
      {
        name: "Oxygen concentrators",
        slug: "oxygen-equipment",
        icon: "🫁",
        type: "category",
        parentCategory: "medical-healthcare",
      },
      {
        name: "CPAP machines",
        slug: "sleep-apnea-equipment",
        icon: "😴",
        type: "category",
        parentCategory: "medical-healthcare",
      },
      {
        name: "Hospital beds",
        slug: "hospital-beds",
        icon: "🛏️",
        type: "category",
        parentCategory: "medical-healthcare",
      },
      {
        name: "Knee scooters",
        slug: "knee-scooters",
        icon: "🛴",
        type: "category",
        parentCategory: "medical-healthcare",
      },
    ],
  },
  {
    name: "Office & Work Equipment",
    shortName: "Office Equipment",
    slug: "office-work",
    icon: "🏢",
    type: "category",
    parentCategory: null,
    subCategories: [
      {
        name: "Desks & office chairs",
        slug: "office-furniture",
        icon: "💺",
        type: "category",
        parentCategory: "office-work",
      },
      {
        name: "Whiteboards & presentation tools",
        slug: "presentation-equipment",
        icon: "📊",
        type: "category",
        parentCategory: "office-work",
      },
      {
        name: "Conference room setups",
        slug: "conference-equipment",
        icon: "🤝",
        type: "category",
        parentCategory: "office-work",
      },
      {
        name: "Portable WiFi routers",
        slug: "wifi-routers",
        icon: "📡",
        type: "category",
        parentCategory: "office-work",
      },
      {
        name: "PA systems & microphones",
        slug: "audio-equipment",
        icon: "🎤",
        type: "category",
        parentCategory: "office-work",
      },
    ],
  },
  {
    name: "Gaming & Entertainment",
    shortName: "Games, Hobbies",
    slug: "gaming-entertainment",
    icon: "🎮",
    type: "category",
    parentCategory: null,
    subCategories: [
      {
        name: "Board games & card games",
        slug: "board-games",
        icon: "🎲",
        type: "category",
        parentCategory: "gaming-entertainment",
      },
      {
        name: "Pool tables & foosball tables",
        slug: "game-tables",
        icon: "🎱",
        type: "category",
        parentCategory: "gaming-entertainment",
      },
      {
        name: "Arcade machines",
        slug: "arcade-machines",
        icon: "🕹️",
        type: "category",
        parentCategory: "gaming-entertainment",
      },
      {
        name: "Karaoke machines",
        slug: "karaoke",
        icon: "🎤",
        type: "category",
        parentCategory: "gaming-entertainment",
      },
      {
        name: "VR gaming setups",
        slug: "vr-gaming",
        icon: "🥽",
        type: "category",
        parentCategory: "gaming-entertainment",
      },
    ],
  },
  {
    name: "Costumes & Cosplay",
    shortName: "Costumes",
    slug: "costumes-cosplay",
    icon: "🎭",
    type: "category",
    parentCategory: null,
    subCategories: [
      {
        name: "Halloween costumes",
        slug: "halloween-costumes",
        icon: "👻",
        type: "category",
        parentCategory: "costumes-cosplay",
      },
      {
        name: "Superhero & anime outfits",
        slug: "character-costumes",
        icon: "🦸",
        type: "category",
        parentCategory: "costumes-cosplay",
      },
      {
        name: "Medieval & fantasy armor",
        slug: "fantasy-costumes",
        icon: "🛡️",
        type: "category",
        parentCategory: "costumes-cosplay",
      },
      {
        name: "Mascot costumes",
        slug: "mascot-costumes",
        icon: "🐻",
        type: "category",
        parentCategory: "costumes-cosplay",
      },
    ],
  },
  {
    name: "Pet Accessories",
    shortName: "Pet Accessories",
    slug: "pet-accessories",
    icon: "🐶",
    type: "category",
    parentCategory: null,
    subCategories: [
      {
        name: "Pet strollers & carriers",
        slug: "pet-transport",
        icon: "🐱",
        type: "category",
        parentCategory: "pet-accessories",
      },
      {
        name: "Temporary pet fences",
        slug: "pet-fences",
        icon: "🚧",
        type: "category",
        parentCategory: "pet-accessories",
      },
      {
        name: "Large pet crates & playpens",
        slug: "pet-crates",
        icon: "🏠",
        type: "category",
        parentCategory: "pet-accessories",
      },
    ],
  },
  {
    name: "Vehicles & Transportation",
    shortName: "Car, Motor",
    slug: "vehicles-transportation",
    icon: "🚗",
    type: "category",
    parentCategory: null,
    subCategories: [
      {
        name: "Rental cars & SUVs",
        slug: "rental-cars",
        icon: "🚙",
        type: "category",
        parentCategory: "vehicles-transportation",
      },
      {
        name: "Motorcycles & scooters",
        slug: "motorcycles",
        icon: "🏍️",
        type: "category",
        parentCategory: "vehicles-transportation",
      },
      {
        name: "RVs & camper vans",
        slug: "rv-campers",
        icon: "🚐",
        type: "category",
        parentCategory: "vehicles-transportation",
      },
      {
        name: "Bicycles & e-scooters",
        slug: "bicycles-scooters",
        icon: "🚲",
        type: "category",
        parentCategory: "vehicles-transportation",
      },
      {
        name: "Boats & jet skis",
        slug: "boats",
        icon: "🚤",
        type: "category",
        parentCategory: "vehicles-transportation",
      },
    ],
  },
];

export default RENTAL_CATEGORIES;
