export const RENTAL_CATEGORIES = [
  {
    name: "Event & Party Supplies",
    slug: "event-party",
    icon: "🎉",
    subCategories: [
      "Chairs & tables (folding, banquet, cocktail)",
      "Tents & canopies",
      "Sound systems & speakers",
      "Projectors & screens",
      "Party decorations (backdrops, banners, balloons)",
      "Lighting equipment (LEDs, fairy lights, stage lighting)",
      "Dance floors & stages",
      "Fog machines & bubble machines",
      "Photo booths & props",
      "Catering equipment (chafing dishes, coolers, beverage dispensers)",
    ],
  },
  {
    name: "Photography & Video Equipment",
    slug: "photography-video",
    icon: "📷",
    subCategories: [
      "DSLR & mirrorless cameras",
      "Camera lenses",
      "Tripods & stabilizers (gimbals)",
      "Drones (DJI, GoPro)",
      "Action cameras (GoPro, Insta360)",
      "Lighting kits (softboxes, ring lights, LED panels)",
      "Green screens",
      "Microphones & audio recorders",
    ],
  },
  {
    name: "Outdoor & Adventure Gear",
    slug: "outdoor-adventure",
    icon: "⛺",
    subCategories: [
      "Camping tents & sleeping bags",
      "Hammocks & air mattresses",
      "Camping stoves & cookware",
      "Fishing rods & tackle",
      "Kayaks, canoes & paddleboards",
      "Surfboards & bodyboards",
      "Bicycles & mountain bikes",
      "Hiking gear (backpacks, trekking poles)",
      "Snowboarding & skiing equipment",
      "Binoculars & GPS devices",
    ],
  },
  {
    name: "Tools & Home Improvement",
    slug: "tools-home",
    icon: "🔨",
    subCategories: [
      "Power tools (drills, saws, sanders)",
      "Ladders & scaffolding",
      "Pressure washers",
      "Carpet cleaners & steam cleaners",
      "Generators & inverters",
      "Tile cutters & flooring tools",
      "Paint sprayers & wallpaper removers",
      "Demolition hammers",
    ],
  },
  {
    name: "Luxury & Specialty Items",
    slug: "luxury-specialty",
    icon: "💎",
    subCategories: [
      "Luxury cars (sports cars, convertibles, limos)",
      "Designer handbags & watches",
      "High-end jewelry & accessories",
      "Vintage & classic cars",
      "Private yachts & boats",
    ],
  },
  {
    name: "Electronics & Tech Gadgets",
    slug: "electronics-tech",
    icon: "💻",
    subCategories: [
      "Laptops & tablets",
      "Gaming consoles (PS5, Xbox, Nintendo Switch)",
      "VR headsets (Oculus, HTC Vive)",
      "Smart projectors & screens",
      "Printers & scanners",
      "Walkie-talkies & communication devices",
    ],
  },
  {
    name: "Wedding & Formal Wear",
    slug: "wedding-formal",
    icon: "👗",
    subCategories: [
      "Wedding dresses & tuxedos",
      "Evening gowns & suits",
      "Accessories (clutches, veils, gloves)",
      "Traditional outfits (kimono, saree, qipao)",
    ],
  },
  {
    name: "Sports & Fitness Equipment",
    slug: "sports-fitness",
    icon: "🏋️‍♂️",
    subCategories: [
      "Treadmills & stationary bikes",
      "Dumbbells & barbells",
      "Yoga mats & resistance bands",
      "Basketballs, soccer balls, volleyball nets",
      "Tennis rackets & golf clubs",
      "Boxing gloves & punching bags",
    ],
  },
  {
    name: "Medical & Healthcare Equipment",
    slug: "medical-healthcare",
    icon: "🏥",
    subCategories: [
      "Wheelchairs & mobility scooters",
      "Crutches & walkers",
      "Oxygen concentrators",
      "CPAP machines",
      "Hospital beds",
      "Knee scooters",
    ],
  },
  {
    name: "Office & Work Equipment",
    slug: "office-work",
    icon: "🏢",
    subCategories: [
      "Desks & office chairs",
      "Whiteboards & presentation tools",
      "Conference room setups",
      "Portable WiFi routers",
      "PA systems & microphones",
    ],
  },
  {
    name: "Gaming & Entertainment",
    slug: "gaming-entertainment",
    icon: "🎮",
    subCategories: [
      "Board games & card games",
      "Pool tables & foosball tables",
      "Arcade machines",
      "Karaoke machines",
      "VR gaming setups",
    ],
  },
  {
    name: "Costumes & Cosplay",
    slug: "costumes-cosplay",
    icon: "🎭",
    subCategories: [
      "Halloween costumes",
      "Superhero & anime outfits",
      "Medieval & fantasy armor",
      "Mascot costumes",
    ],
  },
  {
    name: "Pet Accessories",
    slug: "pet-accessories",
    icon: "🐶",
    subCategories: [
      "Pet strollers & carriers",
      "Temporary pet fences",
      "Large pet crates & playpens",
    ],
  },
  {
    name: "Vehicles & Transportation",
    slug: "vehicles-transportation",
    icon: "🚗",
    subCategories: [
      "Rental cars & SUVs",
      "Motorcycles & scooters",
      "RVs & camper vans",
      "Bicycles & e-scooters",
      "Boats & jet skis",
    ],
  },
];
